#!/bin/bash

if test "x${API_SERVER_PORT}x" == "xx"; then
	API_SERVER_PORT=8000
fi

if test "x${API_SERVER_HOST}x" == "xx"; then
	API_SERVER_HOST=10.237.72.81
fi

if test "x$1x" == "xx"; then
	API_REQUEST_METHOD="-X GET"
else
	API_REQUEST_METHOD="-X $1"
fi

if test "x${REQUEST_PATH}x" == "xx"; then
	REQUEST_PATH=""
fi

if test "x${SWUPD_REPO_URL}x" == "xx"; then
	SWUPD_REPO_URL=""
fi

if test "x${BUNDLE_NAME}x" == "xx"; then
	BUNDLE_NAME=""
fi

curl ${API_REQUEST_METHOD} --noproxy "*" -w "\nHTTP: %{http_code}\n" --no-buffer "http://${API_SERVER_HOST}:${API_SERVER_PORT}/api/swupd${REQUEST_PATH}?name=${BUNDLE_NAME}&url=${SWUPD_REPO_URL}"
